meter:
  device: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0LNNZ6-if00-port0
  level:
    low: 700
    high: 950
    calibration_log: /tmp/ir.log
  gas:
    initial: 5790.80
    reset: false
  update_interval: 60

mqtt:
  broker: geapoh.home.arpa
  port: 1883
  topic: gasmeter-bridge
  #user: mqtt
  #password: "your secret password"
  queue_size: 100
  reconnect_delay:
    min: 2
    max: 64
    exponential: true

logger:
  level: info     # global default: off | error | warn | info | debug | trace
  modules:
    main: info
    meter: trace
    mqtt: info